### ISSUE TITLE
Implement backend deployment using Nginx and Gunicorn or uWsgi

### ISSUE THREAD

**Issue by inovizz** [inovizz/codeXpose#35]
Currently, we are deploying the app in docker using Django dev server but once we progress and plan for production, then this has to be changed.

**Comment by amulya349** [comment]
Hi, I am a Django developer. I would like to take up and create deployment plan using gunicorn and nginx. I have some questions though. 

What I understood from the code is, right now a dockerfile is being created from `docker-compose.yml` which contains the command like migrations and all to be run after the container is created. 

But, this method of deploying by running `python manage.py runserver` is not scalable. So, we want to deploy this using gunicorn which will make the web server scalable. Am I right about this?

**Comment by vermaarun** [comment]
@amulya349  Thanks for showing your interest in codeXpose.
Yes, we want to make it scalable so will use nginx and uwsgi/gunicorn instead of directly running server like `python manage.py runserver` . You can proceed with deployment plan.

**Comment by amulya349** [comment]
While I was trying to run the server, I faced some issues. They were mostly permission related issues. When I ran `python manage.py runserver` with `sudo`, it was successful. But, running with `sudo` is not a good idea. Following is the error:

	(virtual)  ✘ ⚙ batman@batman-pc  ~/work/opensource/codeXpose   master ●  ./virtual/bin/python backend/codexpose/manage.py runserver
	Traceback (most recent call last):
	  File "/usr/lib/python3.6/logging/config.py", line 558, in configure
	    handler = self.configure_handler(handlers[name])
	  File "/usr/lib/python3.6/logging/config.py", line 731, in configure_handler
	    result = factory(**kwargs)
	  File "/usr/lib/python3.6/logging/handlers.py", line 150, in __init__
	    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
	  File "/usr/lib/python3.6/logging/handlers.py", line 57, in __init__
	    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
	  File "/usr/lib/python3.6/logging/__init__.py", line 1030, in __init__
	    StreamHandler.__init__(self, self._open())
	  File "/usr/lib/python3.6/logging/__init__.py", line 1059, in _open
	    return open(self.baseFilename, self.mode, encoding=self.encoding)
	PermissionError: [Errno 13] Permission denied: '/home/batman/work/opensource/codeXpose/backend/codexposecodexpose.log'

	During handling of the above exception, another exception occurred:

	Traceback (most recent call last):
	  File "/home/batman/work/opensource/codeXpose/virtual/lib/python3.6/site-packages/django/utils/autoreload.py", line 225, in wrapper
	    fn(*args, **kwargs)
	  File "/home/batman/work/opensource/codeXpose/virtual/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 112, in inner_run
	    autoreload.raise_last_exception()
	  File "/home/batman/work/opensource/codeXpose/virtual/lib/python3.6/site-packages/django/utils/autoreload.py", line 248, in raise_last_exception
	    raise _exception[1]
	  File "/home/batman/work/opensource/codeXpose/virtual/lib/python3.6/site-packages/django/core/management/__init__.py", line 327, in execute
	    autoreload.check_errors(django.setup)()
	  File "/home/batman/work/opensource/codeXpose/virtual/lib/python3.6/site-packages/django/utils/autoreload.py", line 225, in wrapper
	    fn(*args, **kwargs)
	  File "/home/batman/work/opensource/codeXpose/virtual/lib/python3.6/site-packages/django/__init__.py", line 19, in setup
	    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
	  File "/home/batman/work/opensource/codeXpose/virtual/lib/python3.6/site-packages/django/utils/log.py", line 73, in configure_logging
	    logging_config_func(logging_settings)
	  File "/usr/lib/python3.6/logging/config.py", line 795, in dictConfig
	    dictConfigClass(config).configure()
	  File "/usr/lib/python3.6/logging/config.py", line 566, in configure
	    '%r: %s' % (name, e))
	ValueError: Unable to configure handler 'file': [Errno 13] Permission denied: '/home/batman/work/opensource/codeXpose/backend/codexposecodexpose.log'

The issue was that, in the logging handler setup in settings.py, `'filename': BASE_DIR+'codexpose.log',` which puts the log file outside the project directory (one directory above the root dir of project).Adding a `/` worked:

`'filename': BASE_DIR+'/codexpose.log',`

**Comment by amulya349** [comment]
Also, in the `run_server.sh` script, log directories where being created in /var/ directory, I got the same permission issues. I think we should store the logs in project directory. What are your thoughts?

**Comment by amulya349** [comment]
Also, in `run_server.sh` script, in the first three lines, its creating two directories in `/var/logs` and giving it `777` permission. I couldn't find the use of that directory since django logging handler is storing logs in its project directory.
